server:
  port: 8080
  servlet:
    context-path: /api/v1/admin-bff
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_automated_database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
